theme: jekyll-theme-cayman
title: The title of your site
description: A short description of your site's purpose
show_downloads: true
github:
  zip_url: https://codeload.github.com/mdnaik/test-jekyll-theme/zip/main
  another_url: https://codeload.github.com/mdnaik/test-jekyll-theme/tar.gz/main 
